### ISSUE TITLE
Dependency on disruptor for async logging is missing

### ISSUE THREAD

**Issue by pfurbacher** [kedar-joshi/Thymeleaf-JavaEE-MVC#1]
I could not get the app to deploy as configured. The log showed a number of stack traces, all involving `com.lmax.disruptor.EventTranslatorTwoArg`. Here's just a snippet of one: 

```
java.lang.NoClassDefFoundError: com/lmax/disruptor/EventTranslatorTwoArg
    at org.apache.logging.log4j.core.async.AsyncLoggerConfig.start(AsyncLoggerConfig.java:133)
    ...
```

A bit of googling shows that this error occurs if the Disruptor jar is not on the classpath when an `AsynLogger` is present in a Log4j configuration (e.g., [Missing lmax disruptor jar for log4j2 asynchronous loggers](https://github.com/jurmous/logstash-log4j2/issues/7)). To resolve the problem, I added the following dependency to the `pom.xml` file: 

```
<dependency>
    <groupId>com.lmax</groupId>
    <artifactId>disruptor</artifactId>
    <version>3.3.2</version>
</dependency>
```

Once the dependency was added and the web app was republished, the app ran as expected.

Environment: 
- GlassFish Server Open Source Edition 4.1.1 (build 1)
- Spring Tool Suite: version: 3.7.2.RELEASE; build Id: 201511261048; platform: Eclipse Mars.1 (4.5.1)
- Glassfish Tools plugin: version 8.4.0.201510191754
- java version "1.8.0_72-ea"; Java(TM) SE Runtime Environment (build 1.8.0_72-ea-b05); Java HotSpot(TM) 64-Bit Server VM (build 25.72-b05, mixed mode)

**Comment by kedar-joshi** [comment]
Yes, you are correct. As suggested, I have added the dependency.

Thanks for your input.
